//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _365Drive.Office365.UI.Globalization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Globalization {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Globalization() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("_365Drive.Office365.UI.Globalization.Globalization", typeof(Globalization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About: .
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About Partner: .
        /// </summary>
        public static string AboutPartner {
            get {
                return ResourceManager.GetString("AboutPartner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Partner: .
        /// </summary>
        public static string AccountManager {
            get {
                return ResourceManager.GetString("AccountManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} drives mapped.
        /// </summary>
        public static string AllDrivesMapped {
            get {
                return ResourceManager.GetString("AllDrivesMapped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 365mapper does not support the authentication method used by your Office 365 tenancy.
        /// </summary>
        public static string AuthenticationTypeNotSupported {
            get {
                return ResourceManager.GetString("AuthenticationTypeNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to © Identity Experts Software Limited.
        /// </summary>
        public static string Copyright {
            get {
                return ResourceManager.GetString("Copyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Credentials (Default).
        /// </summary>
        public static string credential_page_header {
            get {
                return ResourceManager.GetString("credential_page_header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string credential_password {
            get {
                return ResourceManager.GetString("credential_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username (Office 365 Logon).
        /// </summary>
        public static string credential_signinname {
            get {
                return ResourceManager.GetString("credential_signinname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please sign in to continue.
        /// </summary>
        public static string CredentialNotPresent {
            get {
                return ResourceManager.GetString("CredentialNotPresent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign In.
        /// </summary>
        public static string credentials {
            get {
                return ResourceManager.GetString("credentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verifying licence.
        /// </summary>
        public static string CredentialsPresent {
            get {
                return ResourceManager.GetString("CredentialsPresent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you for signing in, we will attempt login shortly.
        /// </summary>
        public static string CredentialsReceived {
            get {
                return ResourceManager.GetString("CredentialsReceived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .NET Version.
        /// </summary>
        public static string DotNetVersion {
            get {
                return ResourceManager.GetString("DotNetVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drive details fetched from IE licensing server.
        /// </summary>
        public static string DriveDetailsFound {
            get {
                return ResourceManager.GetString("DriveDetailsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid email address.
        /// </summary>
        public static string emailvalidation {
            get {
                return ResourceManager.GetString("emailvalidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validating credentials.
        /// </summary>
        public static string EnsuringCredential {
            get {
                return ResourceManager.GetString("EnsuringCredential", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking connectivity.
        /// </summary>
        public static string EnsuringInternet {
            get {
                return ResourceManager.GetString("EnsuringInternet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking WebClient service is running.
        /// </summary>
        public static string EnsuringwebClient {
            get {
                return ResourceManager.GetString("EnsuringwebClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exiting application will unmap 365mapper drives, are you sure?.
        /// </summary>
        public static string ExitSure {
            get {
                return ResourceManager.GetString("ExitSure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authentication Method.
        /// </summary>
        public static string Federation {
            get {
                return ResourceManager.GetString("Federation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fetching drive details.
        /// </summary>
        public static string GettingDriveDetails {
            get {
                return ResourceManager.GetString("GettingDriveDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting OneDrive for Business URL.
        /// </summary>
        public static string GettingoneDriveUrl {
            get {
                return ResourceManager.GetString("GettingoneDriveUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intializing 365mapper.
        /// </summary>
        public static string Initializing {
            get {
                return ResourceManager.GetString("Initializing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internet.
        /// </summary>
        public static string InternetConnection {
            get {
                return ResourceManager.GetString("InternetConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Licence.
        /// </summary>
        public static string License {
            get {
                return ResourceManager.GetString("License", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your licence has been activated..
        /// </summary>
        public static string LicenseActivatedFirstTime {
            get {
                return ResourceManager.GetString("LicenseActivatedFirstTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Licence activation or verification failed ({0})..
        /// </summary>
        public static string LicenseActivationFailed {
            get {
                return ResourceManager.GetString("LicenseActivationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to verify the licence details, retrying....
        /// </summary>
        public static string LicenseCouldNotVerified {
            get {
                return ResourceManager.GetString("LicenseCouldNotVerified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Licences expired or exceeded, please contact your IT department.
        /// </summary>
        public static string LicenseExpired {
            get {
                return ResourceManager.GetString("LicenseExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Licence validated.
        /// </summary>
        public static string LicenseFoundOK {
            get {
                return ResourceManager.GetString("LicenseFoundOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Licence validation failed, retrying....
        /// </summary>
        public static string LicenseValidationFailed {
            get {
                return ResourceManager.GetString("LicenseValidationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Licence error.
        /// </summary>
        public static string LicenseValidationFailedHeading {
            get {
                return ResourceManager.GetString("LicenseValidationFailedHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Either credentials not valid or your IT admin has not granted 365 Access to 365mapper app.
        /// </summary>
        public static string LoginFailed {
            get {
                return ResourceManager.GetString("LoginFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mapping drives.....
        /// </summary>
        public static string MappingDrives {
            get {
                return ResourceManager.GetString("MappingDrives", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multi Factor Authentication.
        /// </summary>
        public static string MFA {
            get {
                return ResourceManager.GetString("MFA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you, we will attempt MFA shortly!.
        /// </summary>
        public static string MFAPromtNow {
            get {
                return ResourceManager.GetString("MFAPromtNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your account has been configured by multi factor authentication with default authentication set to {0}..
        /// </summary>
        public static string MFAUserMessage {
            get {
                return ResourceManager.GetString("MFAUserMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please click here to Sign in.
        /// </summary>
        public static string NocredMessage {
            get {
                return ResourceManager.GetString("NocredMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .NET framework 4.5 or higher required.
        /// </summary>
        public static string Nodotnet45 {
            get {
                return ResourceManager.GetString("Nodotnet45", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No internet connectivity found.
        /// </summary>
        public static string NoInternet {
            get {
                return ResourceManager.GetString("NoInternet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your password.
        /// </summary>
        public static string passwordcannotbeblank {
            get {
                return ResourceManager.GetString("passwordcannotbeblank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 365mapper.
        /// </summary>
        public static string ProductName {
            get {
                return ResourceManager.GetString("ProductName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you for your input, we will proceed with MFA later. Meanwhile, If you want to re-enable MFA prompt, click on &apos;Prompt MFA&apos; from menu..
        /// </summary>
        public static string RemindMeLaterNotification {
            get {
                return ResourceManager.GetString("RemindMeLaterNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MFA will be attempted later. To start now, click &apos;Prompt MFA&apos; from menu. .
        /// </summary>
        public static string RemindMeLaterStatus {
            get {
                return ResourceManager.GetString("RemindMeLaterStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 365mapper Settings.
        /// </summary>
        public static string settings {
            get {
                return ResourceManager.GetString("settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We will soon re-check your license status and fetch updated drive mapping details.
        /// </summary>
        public static string settingsrefreshed {
            get {
                return ResourceManager.GetString("settingsrefreshed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign in.
        /// </summary>
        public static string SignInPageheader {
            get {
                return ResourceManager.GetString("SignInPageheader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign out.
        /// </summary>
        public static string SignOut {
            get {
                return ResourceManager.GetString("SignOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signing out will unmap 365mapper drives, are you sure?.
        /// </summary>
        public static string SignoutSure {
            get {
                return ResourceManager.GetString("SignoutSure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You should have received SMS to your registered mobile number, please type that here:.
        /// </summary>
        public static string SMSReceivedMesSage {
            get {
                return ResourceManager.GetString("SMSReceivedMesSage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign in.
        /// </summary>
        public static string Submit {
            get {
                return ResourceManager.GetString("Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Office 365 tenancy is not registered with 365mapper.
        /// </summary>
        public static string TenancyNotRegistered {
            get {
                return ResourceManager.GetString("TenancyNotRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version: .
        /// </summary>
        public static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WebClient Service.
        /// </summary>
        public static string webClient {
            get {
                return ResourceManager.GetString("webClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How to automate and start the WebClient service{0}{0}
        ///
        ///1. Click Start, click in the Start Search box, type services.msc, and then press ENTER.{0}
        ///2. Optionally, export and save a list of the existing settings. To do this, right-click Services, select Export List, and save the settings list.{0}
        ///3. In the details pane, right-click the service that you want to configure, and then click Properties.{0}
        ///4. On the General tab, in Startup type, click Automatic.{0}
        ///5. Click on Start button to start it.{0}
        ///6.  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string webClientHelp {
            get {
                return ResourceManager.GetString("webClientHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WebClient service is not running, click here for help starting it.
        /// </summary>
        public static string webClientNotRunning {
            get {
                return ResourceManager.GetString("webClientNotRunning", resourceCulture);
            }
        }
    }
}
