//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _365Drive.Office365.UI.Globalization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Globalization {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Globalization() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("_365Drive.Office365.UI.Globalization.Globalization", typeof(Globalization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About: .
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All drives mapped.
        /// </summary>
        public static string AllDrivesMapped {
            get {
                return ResourceManager.GetString("AllDrivesMapped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We do not support the authentication type set to your office 365 tenancy. please check with Identity Experts support team..
        /// </summary>
        public static string AuthenticationTypeNotSupported {
            get {
                return ResourceManager.GetString("AuthenticationTypeNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to © Identity Experts Software Ltd..
        /// </summary>
        public static string Copyright {
            get {
                return ResourceManager.GetString("Copyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Credentials (Default).
        /// </summary>
        public static string credential_page_header {
            get {
                return ResourceManager.GetString("credential_page_header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string credential_password {
            get {
                return ResourceManager.GetString("credential_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string credential_username {
            get {
                return ResourceManager.GetString("credential_username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credentials not present, please authenticate to proceed..
        /// </summary>
        public static string CredentialNotPresent {
            get {
                return ResourceManager.GetString("CredentialNotPresent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credential.
        /// </summary>
        public static string credentials {
            get {
                return ResourceManager.GetString("credentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credentials present, moving to verify license.
        /// </summary>
        public static string CredentialsPresent {
            get {
                return ResourceManager.GetString("CredentialsPresent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .NET Version.
        /// </summary>
        public static string DotNetVersion {
            get {
                return ResourceManager.GetString("DotNetVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drive details fetched from IE licensing server.
        /// </summary>
        public static string DriveDetailsFound {
            get {
                return ResourceManager.GetString("DriveDetailsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter valid email address.
        /// </summary>
        public static string emailvalidation {
            get {
                return ResourceManager.GetString("emailvalidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ensuring credentials exist or not. If not, will propmt for it.
        /// </summary>
        public static string EnsuringCredential {
            get {
                return ResourceManager.GetString("EnsuringCredential", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ensuring internet access...
        /// </summary>
        public static string EnsuringInternet {
            get {
                return ResourceManager.GetString("EnsuringInternet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ensuring webClient service is running or not...
        /// </summary>
        public static string EnsuringwebClient {
            get {
                return ResourceManager.GetString("EnsuringwebClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exiting application will unmap all mapped drives, are you sure you want to exit application? .
        /// </summary>
        public static string ExitSure {
            get {
                return ResourceManager.GetString("ExitSure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authentication Method.
        /// </summary>
        public static string Federation {
            get {
                return ResourceManager.GetString("Federation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fetching mappable drive details.
        /// </summary>
        public static string GettingDriveDetails {
            get {
                return ResourceManager.GetString("GettingDriveDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OneDrive for business found to be mapped. Getting its Url.
        /// </summary>
        public static string GettingoneDriveUrl {
            get {
                return ResourceManager.GetString("GettingoneDriveUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intializing 365Drive.
        /// </summary>
        public static string Initializing {
            get {
                return ResourceManager.GetString("Initializing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internet.
        /// </summary>
        public static string InternetConnection {
            get {
                return ResourceManager.GetString("InternetConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We could not verify the license details, 365Drive will attempt again in few seconds.
        /// </summary>
        public static string LicenseCouldNotVerified {
            get {
                return ResourceManager.GetString("LicenseCouldNotVerified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your license has been expired or limit exceeded, kindly contact your administrator.
        /// </summary>
        public static string LicenseExpired {
            get {
                return ResourceManager.GetString("LicenseExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your license information found OK.
        /// </summary>
        public static string LicenseFoundOK {
            get {
                return ResourceManager.GetString("LicenseFoundOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License Validation Failed.
        /// </summary>
        public static string LicenseValidationFailed {
            get {
                return ResourceManager.GetString("LicenseValidationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Either credentials not valid or your IT admin has not granted 365 Access to 365Drive app.
        /// </summary>
        public static string LoginFailed {
            get {
                return ResourceManager.GetString("LoginFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mapping drives.....
        /// </summary>
        public static string MappingDrives {
            get {
                return ResourceManager.GetString("MappingDrives", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We need to authenticate to get started.
        /// </summary>
        public static string NocredMessage {
            get {
                return ResourceManager.GetString("NocredMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We need .NET framework 4.5 or higher to proceed..
        /// </summary>
        public static string Nodotnet45 {
            get {
                return ResourceManager.GetString("Nodotnet45", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oops! looks like you don&apos;t have working internet connection, waiting to get back....
        /// </summary>
        public static string NoInternet {
            get {
                return ResourceManager.GetString("NoInternet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password cannot be blank.
        /// </summary>
        public static string passwordcannotbeblank {
            get {
                return ResourceManager.GetString("passwordcannotbeblank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 365Drive.
        /// </summary>
        public static string ProductName {
            get {
                return ResourceManager.GetString("ProductName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signout.
        /// </summary>
        public static string SignOut {
            get {
                return ResourceManager.GetString("SignOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signing out application will unmap all mapped drives and clear all locally saved settings, are you sure you want to signout?.
        /// </summary>
        public static string SignoutSure {
            get {
                return ResourceManager.GetString("SignoutSure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Submit {
            get {
                return ResourceManager.GetString("Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version: .
        /// </summary>
        public static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WebClient Service.
        /// </summary>
        public static string webClient {
            get {
                return ResourceManager.GetString("webClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WebClient service is not running. Please start it..
        /// </summary>
        public static string webClientNotRunning {
            get {
                return ResourceManager.GetString("webClientNotRunning", resourceCulture);
            }
        }
    }
}
